<a href="https://colab.research.google.com/github/Flyingzaptop/Python-Colab/blob/main/DZ%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [ ]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [ ]:
arr = np.arange(1, 13)
print(arr.shape)
print(arr.dtype)
print(arr)


(12,)
int64
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [ ]:
matr = arr.reshape(3, 4).astype('float32')
print(matr.T)


[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [ ]:
chess_matr = np.zeros((8, 8), dtype=int)
chess_matr[1::2, ::2] = 1
chess_matr[::2, 1::2] = 1
print(chess_matr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [ ]:
rmatrix = np.random.randint(0,100,(4,3))
print(rmatrix)
s1 = rmatrix.sum(axis=0)
s2 = rmatrix.sum(axis=1)
s3 = rmatrix.sum()
print(" ")
print(s1)
print(" ")
print(s2)
print(" ")
print(s3)

[[35 43 42]
 [63 92  6]
 [92 27 97]
 [91 28 30]]
 
[281 190 175]
 
[120 161 216 149]
 
646


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [ ]:
row_max = rmatrix.max(axis=1)
print(s2)

print(" - ")

print(row_max)

s4 = s2 - row_max
print(" = ")

print(s4)

[120 161 216 149]
 - 
[43 92 97 91]
 = 
[ 77  69 119  58]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [ ]:
weights = np.array([5,10,25,40])
boxes = np.array([20,5,10,4])

cargo = weights @ boxes
print(cargo)

print(5*20 + 5*10 + 10*25 +4*40)


560
560


# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [ ]:
boats_num = 5
all_boxes = np.random.randint(0,20,(boats_num, 4))
print(all_boxes)
print(" ")
total = all_boxes @ weights
print(total)

[[ 6 16 13 18]
 [11 15 11  5]
 [ 5  6 16 18]
 [ 7  0  8 12]
 [ 2  9 13 12]]
 
[1235  680 1205  715  905]
